version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:5000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    ports:
      - "4000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kevinguzman
      - POSTGRES_DB=tokenbasedauthdb

volumes:
  postgres_data:
